<div class="row">
    <div class="col-12 col-md-6">

        <!-- Affichage des eventuels messages d'erreur -->
        <?php if (isset($message)): ?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <p><?= $message ?></p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php endif; ?>

        <!-- Formulaire de creation d'annonce -->
        <form action="addListing.php" method="post" enctype="multipart/form-data">
            <h2>
                Ajout d'une annonce
            </h2>
            <div class="row">
                <div class="col-8">
                    <div class="mb-3">
                        <label for="titre" class="form-label">Titre</label>
                        <input type="text" class="form-control" id="titre" name="titre" required>
                    </div>
                </div>
                <div class="col-4">
                    <div class="mb-3">
                        <label for="type" class="form-label">Type</label>
                        <select class="form-select" id="type" name="type">
                            <option value="location">Location</option>
                            <option value="vente">Vente</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="adresse" class="form-label">Adresse</label>
                <input type="text" class="form-control" id="adresse" name="adresse" placeholder="Ex. 123 Rue petite"
                       required>
            </div>
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="mb-3">
                        <label for="ville" class="form-label">Ville</label>
                        <input type="text" class="form-control" id="ville" name="ville" required>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="mb-3">
                        <label for="cp" class="form-label">Code Postal</label>
                        <input type="number" maxlength="5" class="form-control" id="cp" name="cp" required>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-lg-3">
                    <label for="prix" class="form-label">Prix</label>
                    <div class="input-group mb-3">
                        <input type="number" class="form-control" id="prix" name="prix" aria-describedby="euros"
                               required>
                        <span class="input-group-text" id="euros">€</span>
                    </div>
                </div>
                <div class="col-12 col-lg-3">
                    <label for="surface" class="form-label">Surface</label>
                    <div class="input-group mb-3">
                        <input type="number" class="form-control" id="surface" name="surface" aria-describedby="metres"
                               required>
                        <span class="input-group-text" id="metres">m²</span>
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <label for="photo" class="form-label">Photo</label>
                    <div class="input-group mb-3">
                        <input type="file" class="form-control" id="photo" name="photo">
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea class="form-control" id="description" rows="3" name="description"></textarea>
            </div>
            <input type="submit" class="btn btn-primary" value="Publier">
        </form>
    </div>
</div>